version: '3.0'

services:
  nestjs-server-main:
    image: main
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - .:/usr/src/app/node_modules
    depends_on:
      - postgres
    networks:
      - backend
    restart: always
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      POSTGRES_HOST: postgres

  postgres:
    container_name: postgres
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data
    networks:
      - backend
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}

networks:
  backend:
    driver: bridge