version: '3.0'

services:
  # server:
  #   image: server
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - postgres-q4
  #   networks:
  #     - backend
  #   restart: always
  #   ports:
  #     - ${PORT}:${PORT}
  #   environment:
  #     PORT: ${PORT}
  #     POSTGRES_HOST: postgres-q4

  postgres-q4:
    container_name: postgres-q4
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - ./database/postgresdata:/var/lib/postgresql/data
    networks:
      - backend
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}

networks:
  backend:
    driver: bridge